apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-2052
  name: deployment-2052
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2052
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2052
    spec:
      containers:
      - image: nginx:058264449786.dkr.ecr.ap-northeast-1.amazonaws.com/mobi-dev-neo:commit-f16e610
        imagePullPolicy: Always
        name: app-2052
        ports:
        - containerPort: 80
      nodeSelector:
        karpenter.sh/capacity-type: spot
        kubernetes.io/arch: amd64
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - app-2052
            topologyKey: kubernetes.io/hostname
