apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: game-2052
  name: ingress-2052
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
spec:
  ingressClassName: {{ .Values.ingress.type }}
  rules:
    - host: game-2052-{{ .Values.clusterName }}.{{ .Values.ingress.host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-2052
              port:
                number: 80
