# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main 

# jobs:
#   build-and-test:
#     name: Build and Test
#     runs-on: self-hosted 

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     # - name: Build Docker image
#     #   run: sudo docker build ./python -t python-environment

#     # - name: Run Tests
#     #   run: |
#     #     docker run python-environment /bin/sh -c "your test command"

#   deploy:
#     needs: build-and-test
#     runs-on: ubuntu-latest
#     steps:
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ap-northeast-1

#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Login to Amazon ECR
#       run: aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com

#     - name: Build, tag, and push Docker image to Amazon ECR
#       run: |
#         docker build ./app/nginx -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/mobi-dev-neo:latest
#         docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/mobi-dev-neo:latest